### ISSUE TITLE
[Feature request]Use named profiles for aws cli commands in shell actions 

### ISSUE THREAD

**Issue by samveen** [kota65535/terraform-aws-s3-deployment#47]
The official `aws` provider supports the use of `  profile="srsstage"` as a parameter to determine the credentials to be used for all actions taken by terraform.

Please allow for a similar process to use the `--profile` paramter in the shell scripts that are executed as part of this module, as and when a named profile is used, instead of using the default credentials.

Use case:
I do not set up default credentials at all, using named profiles exclusively, given that I have to work with multiple AWS accounts for each of the environments, to protect against accidental changes in the wrong environment. The module as it is today would upload the deployment archive to the incorrect account's bucket if used with named profiles.

**Comment by kota65535** [comment]
Hi @samveen
I've released 1.5.0, and this is how to configure the profile for AWS CLI. Please try it.

```
module "s3_deployment" {
  ...
  
  aws_config = {
    profile = "foobar"
  }
}

```
